<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ANGELITO2024" failures="1" tests="1" name="Default test" time="0.078" errors="0" timestamp="2024-11-12T08:16:36 GMT-05:00">
  <testcase classname="com.magento.tests.RegisterTest" name="doConfirPasswordSecurity" time="0.021">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void com.magento.tests.RegisterTest.doConfirPasswordSecurity(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,boolean)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: doConfirPasswordSecurity([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, boolean arg5])
Arguments: [(java.lang.String) angel,(java.lang.String) chavez,(java.lang.String) angel46_318@hotmail.com,(java.lang.String) TingoMaria90@,(java.lang.String) TingoMaria90@]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.magento.tests.RegisterTest.doConfirPasswordSecurity(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,boolean)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: doConfirPasswordSecurity([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4, boolean arg5])
Arguments: [(java.lang.String) angel,(java.lang.String) chavez,(java.lang.String) angel46_318@hotmail.com,(java.lang.String) TingoMaria90@,(java.lang.String) TingoMaria90@]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:915)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- doConfirPasswordSecurity -->
</testsuite> <!-- Default test -->
